#!/usr/bin/python

import argparse
import sys

from HSVerifyd.AuthFile import AuthFile
from HSVerifyd.Daemonize import Daemonize

__application__ = "HSVerifyd"
__version__ = "0.1.0"
__release__ = __application__ + '/' + __version__
__author__ = "Juan Ezquerro LLanes"

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--start', help='Start Server', action="store_true")
    parser.add_argument('--stop', help='Stop Server', action="store_true")
    parser.add_argument('--restart', help='Restart Server', action="store_true")
    parser.add_argument('--sign', help='Sign the services offered by this domain', action="store_true")
    args = parser.parse_args()

    # Sign the services
    if args.json:
        auth = AuthFile()
        auth.sign()
        sys.exit(0)

    # Daemon manager
    daemon = Daemonize()

    if args.start:
        daemon.start()
    elif args.stop:
        daemon.stop()
    elif args.restart:
        daemon.restart()
    else:
        parser.print_help()
